"""Initial migrations

Revision ID: 0dcba5535af0
Revises: 
Create Date: 2023-05-28 11:21:38.149896

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0dcba5535af0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__chats'))
    )
    op.create_table('messages',
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__messages'))
    )
    op.create_table('chat_participants',
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk__chat_participants__chat_id__chats')),
    sa.PrimaryKeyConstraint('chat_id', 'participant_id', name=op.f('pk__chat_participants'))
    )
    op.create_table('messages_participants',
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk__messages_participants__message_id__messages')),
    sa.PrimaryKeyConstraint('message_id', 'participant_id', name=op.f('pk__messages_participants'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_participants')
    op.drop_table('chat_participants')
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
