"""Add chat_id to messages_participants table

Revision ID: 427fe58301bc
Revises: 0dcba5535af0
Create Date: 2023-05-29 08:47:43.481740

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '427fe58301bc'
down_revision = '0dcba5535af0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages_participants', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__messages_participants__chat_id__chats'), 'messages_participants', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__messages_participants__chat_id__chats'), 'messages_participants', type_='foreignkey')
    op.drop_column('messages_participants', 'chat_id')
    # ### end Alembic commands ###
