from models import Chat, ChatParticipant, Message, MessagesToParticipants


# Добавьте сюда таблицы для генерации миграций для них
autogenerated_tables = (Chat, ChatParticipant, Message, MessagesToParticipants)


__all__ = (
    "autogenerated_tables",
)
